### PR TITLE
dev: Use Storybook for component testing

### PR DESCRIPTION
**Pull request by mastercactapus**
**Description:**
This PR replaces the playwright experimental component testing stuff with Storybook.js

- Ability to mock GraphQL query/mutations included /w example tests
- Stories and tests added for the `Time` component
- Stories and tests added for the `TelTextField` component
- Deleted playwright component tests, hacks, and config
- Made `timeFormat` support unix timestamps in addition to ISO and DateTime
- Fixed an issue we found with `make vscode`

Start the UI with `make storybook`
Test components remains `make test-components`

**Screenshots:**
image
image

**Describe any introduced user-facing changes:**
N/A

**Describe any introduced API changes:**
N/A

### CODE REVIEW

**Comment by Forfold** [comment]
The Valid TelTextField demo is rendering as invalid:

Screenshot 2024-01-04 at 10 42 58 AM

**Comment by Forfold** [comment]
Clicking on "Valid Number" from the sidebar produces this error:

Screenshot 2024-01-04 at 10 44 41 AM

**Comment by Forfold** [comment]
If I refresh the page, the screen turns white and the console has the following errors:

Screenshot 2024-01-04 at 10 46 53 AM

**Comment by Forfold** [comment]
Running `make generate` beforehand resolves the above errors ^ Though there is still the issue of the valid TelTextField showing as invalid

**Review by tony-tvu — DISMISSED** [review]
LGTM

**Review by tony-tvu — DISMISSED** [review]

**Review by Forfold — APPROVED** [review]
It would be nice if we could reduce the time to test- Currently sitting around 1-2 minutes for me. Storybook also takes at least a minute to render the components. Otherwise, looks good.

Screenshot 2024-01-05 at 10 00 56 AM

**Review by tony-tvu — APPROVED** [review]

**Pull request merged**
