### PR TITLE
Breakdown service.spec.ts test logically 

### LINKED ISSUE #3622: playwright: separate out tests logically
With the playwright tests, most assertions are batched within one large function, per page. I think it would help us immensely if we separated these out. It can be time consuming trying to determine what part of the UI is failing when looking at build failures (see: https://ci.dev.target.goalert.me/builds/32693933).

For reference, the services spec is over 400 lines long, and is a single test.

### PR DESCRIPTION
**Pull request by c0d33ngr**
- [x] Identified the issue which this PR solves.
- [x] Read the [**CONTRIBUTING**](https://github.com/target/goalert/blob/master/CONTRIBUTING.md) document.
- [x] Code builds clean without any errors or warnings.
- [ ] Added appropriate tests for any new functionality.
- [x] All new and existing tests passed.
- [x] Added comments in the code, where necessary.
- [x] Ran `make check` to catch common errors. Fixed any that came up.

**Description:**
This issue breakdown the only test available in `service.spec.ts` file into smaller test cases for ease of read.

**Which issue(s) this PR fixes:**
Fixes #3622

### CODE REVIEW

**Comment by c0d33ngr** [comment]
Hi, I'm working in fixing the failing test cases about 20 total(wide & mobile) but I was able to run the ```make playwright-run``` successfully by changing the login timeout to ```60000```. It seem ```30000``` wasn't enough or something

**Comment by mastercactapus** [comment]
hmm, that still seems like a long time for it to hang/wait -- I'll take a look this week; login should be much quicker

**Comment by c0d33ngr** [comment]
All the breakdown tests runs successfully now when I run ``make playwright-run`` with ``60000`` as timeout login

**Comment by mastercactapus** [comment]
@c0d33ngr sorry for the wait on this one, looks like maybe a commit is missing? seeing some typescript errors in a few places

For the login delay, I'm not seeing that -- is it every time for you?

**Comment by c0d33ngr** [comment]
@mastercactapus I understand. About the errors, I forgot to run ```make check``` after making changes but it's fixed now.
Also about login timeout when it was  ```30000``` before now tests didn't run but they run now. My dev setup is Github Codespace
Desktop screenshot

**Review by mastercactapus — APPROVED** [review]
I see, when sufficiently cpu-bound they do run slower, but I'm not seeing any issues on my end otherwise -- looks good, thank you and sorry about the delay getting to this

**Review by tony-tvu — APPROVED** [review]

**Pull request merged**
