### PR TITLE
status updates: switch to per-contact-method behavior

### PR DESCRIPTION
**Pull request by mastercactapus**
**Description:**
This PR changes the behavior of status updates to be a per-contact-method setting, instead of a global user-level setting.

**Which issue(s) this PR fixes:**
Related to #2712 

**Screenshots:**
image

**Describe any introduced user-facing changes:**
- Users can now control if status updates are enabled for a specific contact method.
- Status updates will only activate on contact methods that receive an initial notification.

**Describe any introduced API changes:**
- New `statusUpdates` field on `UserContactMethod` and `enableStatusUpdates` on `UpdateUserContactMethodInput`

**Additional Context**
- Creating a Slack DM contact method should create an entry in `auth_subjects`
- Deleting the contact method should remove it
- This should be reflected in alert notifications (e.g., ack should work with a CM)
- "linking" via an alert ack button should result in a contact method being created

Slack DM functionality is behind a feature flag, test with `make start EXPERIMENTAL=slack-dm`

### CODE REVIEW

**Review by Forfold — CHANGES_REQUESTED** [review]
I had to run `make regendb` to get things working- not sure if this is expected with the new migration.

I also got an unexpected error when attempting to enable status updates for my SMS contact method via the UI:

```
AuthSource="SourceTypeAuthProvider{c7d64ef8-309a-40a4-bf75-9cee7ce3fe04}" AuthUserID=33d00c33-04ce-44c8-b729-e0f114257d27 RequestID=da7562d1-8f9c-4734-bde1-1d1171144d8d error="input: updateUserContactMethod sql: expected 4 arguments, got 3" host=sendit.dev.target.goalert.me http_method=POST http_proto=HTTP/1.1 referer="https://sendit.dev.target.goalert.me/cook/users/33d00c33-04ce-44c8-b729-e0f114257d27" remote_addr="127.0.0.1:52093" uri=/cook/api/graphql x_forwarded_for="98.246.168.48, 136.226.55.2, 35.190.115.218, 35.191.10.92, yamux" x_forwarded_host=
```

**Comment by Forfold** [comment]
Do I need to regendb again? I thought the new migration up would apply on make start

**Comment by Forfold** [comment]
I got an unexpected error when attempting to enable status updates for my SMS contact method via the UI:

```
AuthSource="SourceTypeAuthProvider{c7d64ef8-309a-40a4-bf75-9cee7ce3fe04}" AuthUserID=33d00c33-04ce-44c8-b729-e0f114257d27 RequestID=da7562d1-8f9c-4734-bde1-1d1171144d8d error="input: updateUserContactMethod sql: expected 4 arguments, got 3" host=sendit.dev.target.goalert.me http_method=POST http_proto=HTTP/1.1 referer="https://sendit.dev.target.goalert.me/cook/users/33d00c33-04ce-44c8-b729-e0f114257d27" remote_addr="127.0.0.1:52093" uri=/cook/api/graphql x_forwarded_for="98.246.168.48, 136.226.55.2, 35.190.115.218, 35.191.10.92, yamux" x_forwarded_host=
```

**Comment by mastercactapus** [comment]
@Forfold For the `regendb` -- that's possible. We've had a lot of migrations in different branches/PRs recently, and switching between them can leave things out of order. It's okay if the order doesn't change after going to master. When reviewing, the critical bit is that new migration files are always at the end of the list when sorted alphabetically.

The SQL error was a bug; I pushed a fix.

**Review by Forfold — DISMISSED** [review]
lgtm!

**Review by Forfold — DISMISSED** [review]

**Review by Forfold — APPROVED** [review]

**Review by m17ch — APPROVED** [review]

**Pull request merged**
