### PR TITLE
ui: fix slack link typography in dialog

### PR DESCRIPTION
**Pull request by Forfold**
Adds proper typography to the dialog when linking from Slack to GoAlert.

From:

Screenshot 2023-04-28 at 10 31 04 AM

To:

Screenshot 2023-04-28 at 10 30 44 AM

### CODE REVIEW

**Review by allending313 — COMMENTED** [review]
There seems to be some node errors but it looks good otherwise

**Comment by Forfold** [comment]
@allending313 yeah it looks like it's affecting multiple PRs. I think its stemming from the luxon update here: #2677

**Comment by allending313** [comment]
> @allending313 yeah it looks like it's affecting multiple PRs. I think its stemming from the luxon update here: #2849
oh, that's fun

**Review by allending313 — DISMISSED** [review]

**Review by mastercactapus — CHANGES_REQUESTED** [review]
Can we revert the lockfile change and address that separately?

**Review by mastercactapus — APPROVED** [review]

**Review by allending313 — APPROVED** [review]

**Pull request merged**
