### PR TITLE
add label chips to service details

### PR DESCRIPTION
**Pull request by mastercactapus**
**Description:**
This PR adds chips on the service details page for configured labels.

**Which issue(s) this PR fixes:**
Part of #3425 

**Screenshots:**
image

**Describe any introduced user-facing changes:**
Service details page will now display any labels under the escalation policy.

**Describe any introduced API changes:**
N/A

### CODE REVIEW

**Review by Forfold — COMMENTED** [review]
I think below the escalation policy is a good placement for it, but perhaps we should put it under the icon? that way it won't feel as constrained to fit, and wrapping won't be an issue if multiple labels are present

**Comment by mastercactapus** [comment]
@Forfold, I moved them to their own section in the `DetailsPage` component. It seemed fitting since other types will be adopting labels in the future, too.

**Review by Forfold — CHANGES_REQUESTED** [review]
Two small things related to padding, can we:
- Reduce the bottom/top padding of the description text, and
- Add padding to the chips (maybe put in a grid?)

I can push this up if you want!

Screenshot 2023-12-26 at 8 20 51 PM

**Comment by mastercactapus** [comment]
@Forfold, that would be great, ty :)

**Review by Forfold — APPROVED** [review]
Here is the updated padding:

Screenshot 2023-12-28 at 9 07 19 AM

LGTM!

**Review by KatieMSB — APPROVED** [review]

**Pull request merged**
