### PR TITLE
ui/sched: always use Dest API

### PR DESCRIPTION
**Pull request by mastercactapus**
**Description:**
Updates schedule on-call notifications always to use the new dest API.

**Which issue(s) this PR fixes:**
Part of #2639 

**Describe any introduced user-facing changes:**
N/A

**Describe any introduced API changes:**
N/A

**Additional Info:**
- Fixed issue with dest dialogs where incorrect times were recorded when sched. TZ was different than local

### CODE REVIEW

**Comment by mastercactapus** [comment]
Waiting for #3779 to merge

**Review by allending313 — DISMISSED** [review]

**Review by Forfold — COMMENTED** [review]
I'm not seeing a quick link appear for on-call notifications, however if I go to the link manually, it exists. It looks like we hide the link if slack/webhooks is disabled. Is this intended behavior at this point with destinations being dynamic?

Screenshot 2024-05-14 at 11 54 16 AM

```
        ].concat(
          // only slack/webhook supported atm, so hide the link if disabled
          slackEnabled || webhookEnabled
            ? [
                {
                  label: 'On-Call Notifications',
                  url: 'on-call-notifications',
```

**Comment by Forfold** [comment]
Looks like we hide the link if slack/webhooks is disabled. Is this intended behavior at this point with destinations being dynamic?

**Comment by mastercactapus** [comment]
@Forfold It's existing behavior untouched by this work. I agree it should be changed but maybe do that in it's own PR since there may be a bit of refactoring and dialog updates to handle no valid types.

**Comment by Forfold** [comment]
Gotcha. As long as we don't lose track of it..

**Review by Forfold — APPROVED** [review]

**Pull request merged**
