### PR TITLE
ui: splash screen from index.html

### PR DESCRIPTION
**Pull request by Forfold**
**Description:**
This PR updates the current app-wide suspense logic in place of a splash screen embedded in the `index.html`. This still solves the issue of the app screen flickering in when not logged in (and vice verse with the login screen), but instead shows a gif of the new brand logo with 3 loading dots.

**Other Changes:**
- Branding has been updated for the GoAlert logo app-wide
- Sidebar width slightly decreased to account for new logo sizing

**How to test:**
1. Delete the folder `web/src/build/static`
2. Run `yarn esbuild` to regenerate it (pre-run `yarn` if needed to install the latest deps)
3. Run `make start`
4. To see the logo for longer, open the browser console and navigate to the Network tab
5. Click "No throttling" in the header to open the drop down, then select "Slow 3G"
6. Refresh the page

<details>
<summary>Screenshots:</summary>

Screenshot 2023-12-06 at 7 31 53 AM

Screenshot 2023-12-06 at 7 31 41 AM

Screenshot 2023-12-06 at 7 32 09 AM

Screenshot 2023-12-06 at 7 32 35 AM

Screenshot 2023-12-06 at 7 32 48 AM

splash_logo
</details>

### CODE REVIEW

**Comment by mastercactapus** [comment]
For the logo images -- is it possible to switch entirely to SVG? If so we could just have 1 or 2 files (3 incl. gif -- though it may be possible to animate the SVG too) with vector images we wouldn't need to maintain separate scaling versions

**Comment by Forfold** [comment]
@mastercactapus I was under the impression that `webp` is best for the web after my research, but we do have svgs available that I can use instead of the `webp` source-set, if you'd prefer

**Comment by mastercactapus** [comment]
webp would be better than png, but since we _have_ SVG as an option, it might be worth a little time to see if it's feasible to have a single source of truth; less maintenance, less data in git.

That said I'm open to learning about what you found, my impression is SVG/vector is ideal if you have it since it cleanly scales up and down, and WebP is best if you're working with raster images.

I have a little experience animating svgs too if you want to explore that.

**Review by tony-tvu — APPROVED** [review]
LGTM!

**Review by KatieMSB — APPROVED** [review]

**Review by tony-tvu — DISMISSED** [review]

**Review by KatieMSB — APPROVED** [review]

**Review by tony-tvu — APPROVED** [review]

**Review by KatieMSB — APPROVED** [review]

**Review by mastercactapus — APPROVED** [review]

**Pull request merged**
